/*
Http Gateway

Contains interface documents such as accounts, assets, transactions, etc.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAppScanSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppScanSecret{}

// GetAppScanSecret 获取AppScanSecret响应
type GetAppScanSecret struct {
	// secret，base64 url格式
	Secret *string `json:"secret,omitempty"`
}

// NewGetAppScanSecret instantiates a new GetAppScanSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppScanSecret() *GetAppScanSecret {
	this := GetAppScanSecret{}
	return &this
}

// NewGetAppScanSecretWithDefaults instantiates a new GetAppScanSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppScanSecretWithDefaults() *GetAppScanSecret {
	this := GetAppScanSecret{}
	return &this
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *GetAppScanSecret) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAppScanSecret) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *GetAppScanSecret) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *GetAppScanSecret) SetSecret(v string) {
	o.Secret = &v
}

func (o GetAppScanSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppScanSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableGetAppScanSecret struct {
	value *GetAppScanSecret
	isSet bool
}

func (v NullableGetAppScanSecret) Get() *GetAppScanSecret {
	return v.value
}

func (v *NullableGetAppScanSecret) Set(val *GetAppScanSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppScanSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppScanSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppScanSecret(val *GetAppScanSecret) *NullableGetAppScanSecret {
	return &NullableGetAppScanSecret{value: val, isSet: true}
}

func (v NullableGetAppScanSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppScanSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


