/*
Http Gateway

Contains interface documents such as accounts, assets, transactions, etc.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetMaxCreateOrderSizeParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMaxCreateOrderSizeParam{}

// GetMaxCreateOrderSizeParam 获取最大下单数量-请求
type GetMaxCreateOrderSizeParam struct {
	// 账户id
	AccountId *string `json:"accountId,omitempty"`
	// 所属合约id
	ContractId *string `json:"contractId,omitempty"`
	// 下单价格
	Price *string `json:"price,omitempty"`
}

// NewGetMaxCreateOrderSizeParam instantiates a new GetMaxCreateOrderSizeParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMaxCreateOrderSizeParam() *GetMaxCreateOrderSizeParam {
	this := GetMaxCreateOrderSizeParam{}
	return &this
}

// NewGetMaxCreateOrderSizeParamWithDefaults instantiates a new GetMaxCreateOrderSizeParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMaxCreateOrderSizeParamWithDefaults() *GetMaxCreateOrderSizeParam {
	this := GetMaxCreateOrderSizeParam{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSizeParam) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSizeParam) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSizeParam) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *GetMaxCreateOrderSizeParam) SetAccountId(v string) {
	o.AccountId = &v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSizeParam) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSizeParam) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSizeParam) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *GetMaxCreateOrderSizeParam) SetContractId(v string) {
	o.ContractId = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSizeParam) GetPrice() string {
	if o == nil || IsNil(o.Price) {
		var ret string
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSizeParam) GetPriceOk() (*string, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSizeParam) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given string and assigns it to the Price field.
func (o *GetMaxCreateOrderSizeParam) SetPrice(v string) {
	o.Price = &v
}

func (o GetMaxCreateOrderSizeParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMaxCreateOrderSizeParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.ContractId) {
		toSerialize["contractId"] = o.ContractId
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableGetMaxCreateOrderSizeParam struct {
	value *GetMaxCreateOrderSizeParam
	isSet bool
}

func (v NullableGetMaxCreateOrderSizeParam) Get() *GetMaxCreateOrderSizeParam {
	return v.value
}

func (v *NullableGetMaxCreateOrderSizeParam) Set(val *GetMaxCreateOrderSizeParam) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMaxCreateOrderSizeParam) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMaxCreateOrderSizeParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMaxCreateOrderSizeParam(val *GetMaxCreateOrderSizeParam) *NullableGetMaxCreateOrderSizeParam {
	return &NullableGetMaxCreateOrderSizeParam{value: val, isSet: true}
}

func (v NullableGetMaxCreateOrderSizeParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMaxCreateOrderSizeParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


