/*
Http Gateway

Contains interface documents such as accounts, assets, transactions, etc.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelOrderByIdParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelOrderByIdParam{}

// CancelOrderByIdParam 取消委托单-请求
type CancelOrderByIdParam struct {
	// 账户id
	AccountId *string `json:"accountId,omitempty"`
	// 委托单id
	OrderIdList []string `json:"orderIdList"`
}

type _CancelOrderByIdParam CancelOrderByIdParam

// NewCancelOrderByIdParam instantiates a new CancelOrderByIdParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelOrderByIdParam(orderIdList []string) *CancelOrderByIdParam {
	this := CancelOrderByIdParam{}
	this.OrderIdList = orderIdList
	return &this
}

// NewCancelOrderByIdParamWithDefaults instantiates a new CancelOrderByIdParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelOrderByIdParamWithDefaults() *CancelOrderByIdParam {
	this := CancelOrderByIdParam{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CancelOrderByIdParam) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelOrderByIdParam) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CancelOrderByIdParam) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CancelOrderByIdParam) SetAccountId(v string) {
	o.AccountId = &v
}

// GetOrderIdList returns the OrderIdList field value
func (o *CancelOrderByIdParam) GetOrderIdList() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OrderIdList
}

// GetOrderIdListOk returns a tuple with the OrderIdList field value
// and a boolean to check if the value has been set.
func (o *CancelOrderByIdParam) GetOrderIdListOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderIdList, true
}

// SetOrderIdList sets field value
func (o *CancelOrderByIdParam) SetOrderIdList(v []string) {
	o.OrderIdList = v
}

func (o CancelOrderByIdParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelOrderByIdParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	toSerialize["orderIdList"] = o.OrderIdList
	return toSerialize, nil
}

func (o *CancelOrderByIdParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orderIdList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelOrderByIdParam := _CancelOrderByIdParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelOrderByIdParam)

	if err != nil {
		return err
	}

	*o = CancelOrderByIdParam(varCancelOrderByIdParam)

	return err
}

type NullableCancelOrderByIdParam struct {
	value *CancelOrderByIdParam
	isSet bool
}

func (v NullableCancelOrderByIdParam) Get() *CancelOrderByIdParam {
	return v.value
}

func (v *NullableCancelOrderByIdParam) Set(val *CancelOrderByIdParam) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelOrderByIdParam) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelOrderByIdParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelOrderByIdParam(val *CancelOrderByIdParam) *NullableCancelOrderByIdParam {
	return &NullableCancelOrderByIdParam{value: val, isSet: true}
}

func (v NullableCancelOrderByIdParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelOrderByIdParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


