/*
Http Gateway

Contains interface documents such as accounts, assets, transactions, etc.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PageDataAccountAssetSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageDataAccountAssetSnapshot{}

// PageDataAccountAssetSnapshot 通用翻页返回
type PageDataAccountAssetSnapshot struct {
	// 数据列表
	DataList []AccountAssetSnapshot `json:"dataList,omitempty"`
	// 获取下一页偏移。如果没有下一页数据，则为空串
	NextPageOffsetData *string `json:"nextPageOffsetData,omitempty"`
}

// NewPageDataAccountAssetSnapshot instantiates a new PageDataAccountAssetSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageDataAccountAssetSnapshot() *PageDataAccountAssetSnapshot {
	this := PageDataAccountAssetSnapshot{}
	return &this
}

// NewPageDataAccountAssetSnapshotWithDefaults instantiates a new PageDataAccountAssetSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageDataAccountAssetSnapshotWithDefaults() *PageDataAccountAssetSnapshot {
	this := PageDataAccountAssetSnapshot{}
	return &this
}

// GetDataList returns the DataList field value if set, zero value otherwise.
func (o *PageDataAccountAssetSnapshot) GetDataList() []AccountAssetSnapshot {
	if o == nil || IsNil(o.DataList) {
		var ret []AccountAssetSnapshot
		return ret
	}
	return o.DataList
}

// GetDataListOk returns a tuple with the DataList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageDataAccountAssetSnapshot) GetDataListOk() ([]AccountAssetSnapshot, bool) {
	if o == nil || IsNil(o.DataList) {
		return nil, false
	}
	return o.DataList, true
}

// HasDataList returns a boolean if a field has been set.
func (o *PageDataAccountAssetSnapshot) HasDataList() bool {
	if o != nil && !IsNil(o.DataList) {
		return true
	}

	return false
}

// SetDataList gets a reference to the given []AccountAssetSnapshot and assigns it to the DataList field.
func (o *PageDataAccountAssetSnapshot) SetDataList(v []AccountAssetSnapshot) {
	o.DataList = v
}

// GetNextPageOffsetData returns the NextPageOffsetData field value if set, zero value otherwise.
func (o *PageDataAccountAssetSnapshot) GetNextPageOffsetData() string {
	if o == nil || IsNil(o.NextPageOffsetData) {
		var ret string
		return ret
	}
	return *o.NextPageOffsetData
}

// GetNextPageOffsetDataOk returns a tuple with the NextPageOffsetData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageDataAccountAssetSnapshot) GetNextPageOffsetDataOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageOffsetData) {
		return nil, false
	}
	return o.NextPageOffsetData, true
}

// HasNextPageOffsetData returns a boolean if a field has been set.
func (o *PageDataAccountAssetSnapshot) HasNextPageOffsetData() bool {
	if o != nil && !IsNil(o.NextPageOffsetData) {
		return true
	}

	return false
}

// SetNextPageOffsetData gets a reference to the given string and assigns it to the NextPageOffsetData field.
func (o *PageDataAccountAssetSnapshot) SetNextPageOffsetData(v string) {
	o.NextPageOffsetData = &v
}

func (o PageDataAccountAssetSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageDataAccountAssetSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataList) {
		toSerialize["dataList"] = o.DataList
	}
	if !IsNil(o.NextPageOffsetData) {
		toSerialize["nextPageOffsetData"] = o.NextPageOffsetData
	}
	return toSerialize, nil
}

type NullablePageDataAccountAssetSnapshot struct {
	value *PageDataAccountAssetSnapshot
	isSet bool
}

func (v NullablePageDataAccountAssetSnapshot) Get() *PageDataAccountAssetSnapshot {
	return v.value
}

func (v *NullablePageDataAccountAssetSnapshot) Set(val *PageDataAccountAssetSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullablePageDataAccountAssetSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullablePageDataAccountAssetSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageDataAccountAssetSnapshot(val *PageDataAccountAssetSnapshot) *NullablePageDataAccountAssetSnapshot {
	return &NullablePageDataAccountAssetSnapshot{value: val, isSet: true}
}

func (v NullablePageDataAccountAssetSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageDataAccountAssetSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


