/*
Http Gateway

Contains interface documents such as accounts, assets, transactions, etc.

API version: v1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetMaxCreateOrderSize type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMaxCreateOrderSize{}

// GetMaxCreateOrderSize 获取最大下单数量-响应
type GetMaxCreateOrderSize struct {
	// 最大买入size
	MaxBuySize *string `json:"maxBuySize,omitempty"`
	// 最大卖出size
	MaxSellSize *string `json:"maxSellSize,omitempty"`
	// 最优askPrice
	Ask1Price *string `json:"ask1Price,omitempty"`
	// 最优bidPrice
	Bid1Price *string `json:"bid1Price,omitempty"`
}

// NewGetMaxCreateOrderSize instantiates a new GetMaxCreateOrderSize object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMaxCreateOrderSize() *GetMaxCreateOrderSize {
	this := GetMaxCreateOrderSize{}
	return &this
}

// NewGetMaxCreateOrderSizeWithDefaults instantiates a new GetMaxCreateOrderSize object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMaxCreateOrderSizeWithDefaults() *GetMaxCreateOrderSize {
	this := GetMaxCreateOrderSize{}
	return &this
}

// GetMaxBuySize returns the MaxBuySize field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSize) GetMaxBuySize() string {
	if o == nil || IsNil(o.MaxBuySize) {
		var ret string
		return ret
	}
	return *o.MaxBuySize
}

// GetMaxBuySizeOk returns a tuple with the MaxBuySize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSize) GetMaxBuySizeOk() (*string, bool) {
	if o == nil || IsNil(o.MaxBuySize) {
		return nil, false
	}
	return o.MaxBuySize, true
}

// HasMaxBuySize returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSize) HasMaxBuySize() bool {
	if o != nil && !IsNil(o.MaxBuySize) {
		return true
	}

	return false
}

// SetMaxBuySize gets a reference to the given string and assigns it to the MaxBuySize field.
func (o *GetMaxCreateOrderSize) SetMaxBuySize(v string) {
	o.MaxBuySize = &v
}

// GetMaxSellSize returns the MaxSellSize field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSize) GetMaxSellSize() string {
	if o == nil || IsNil(o.MaxSellSize) {
		var ret string
		return ret
	}
	return *o.MaxSellSize
}

// GetMaxSellSizeOk returns a tuple with the MaxSellSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSize) GetMaxSellSizeOk() (*string, bool) {
	if o == nil || IsNil(o.MaxSellSize) {
		return nil, false
	}
	return o.MaxSellSize, true
}

// HasMaxSellSize returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSize) HasMaxSellSize() bool {
	if o != nil && !IsNil(o.MaxSellSize) {
		return true
	}

	return false
}

// SetMaxSellSize gets a reference to the given string and assigns it to the MaxSellSize field.
func (o *GetMaxCreateOrderSize) SetMaxSellSize(v string) {
	o.MaxSellSize = &v
}

// GetAsk1Price returns the Ask1Price field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSize) GetAsk1Price() string {
	if o == nil || IsNil(o.Ask1Price) {
		var ret string
		return ret
	}
	return *o.Ask1Price
}

// GetAsk1PriceOk returns a tuple with the Ask1Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSize) GetAsk1PriceOk() (*string, bool) {
	if o == nil || IsNil(o.Ask1Price) {
		return nil, false
	}
	return o.Ask1Price, true
}

// HasAsk1Price returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSize) HasAsk1Price() bool {
	if o != nil && !IsNil(o.Ask1Price) {
		return true
	}

	return false
}

// SetAsk1Price gets a reference to the given string and assigns it to the Ask1Price field.
func (o *GetMaxCreateOrderSize) SetAsk1Price(v string) {
	o.Ask1Price = &v
}

// GetBid1Price returns the Bid1Price field value if set, zero value otherwise.
func (o *GetMaxCreateOrderSize) GetBid1Price() string {
	if o == nil || IsNil(o.Bid1Price) {
		var ret string
		return ret
	}
	return *o.Bid1Price
}

// GetBid1PriceOk returns a tuple with the Bid1Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMaxCreateOrderSize) GetBid1PriceOk() (*string, bool) {
	if o == nil || IsNil(o.Bid1Price) {
		return nil, false
	}
	return o.Bid1Price, true
}

// HasBid1Price returns a boolean if a field has been set.
func (o *GetMaxCreateOrderSize) HasBid1Price() bool {
	if o != nil && !IsNil(o.Bid1Price) {
		return true
	}

	return false
}

// SetBid1Price gets a reference to the given string and assigns it to the Bid1Price field.
func (o *GetMaxCreateOrderSize) SetBid1Price(v string) {
	o.Bid1Price = &v
}

func (o GetMaxCreateOrderSize) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMaxCreateOrderSize) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxBuySize) {
		toSerialize["maxBuySize"] = o.MaxBuySize
	}
	if !IsNil(o.MaxSellSize) {
		toSerialize["maxSellSize"] = o.MaxSellSize
	}
	if !IsNil(o.Ask1Price) {
		toSerialize["ask1Price"] = o.Ask1Price
	}
	if !IsNil(o.Bid1Price) {
		toSerialize["bid1Price"] = o.Bid1Price
	}
	return toSerialize, nil
}

type NullableGetMaxCreateOrderSize struct {
	value *GetMaxCreateOrderSize
	isSet bool
}

func (v NullableGetMaxCreateOrderSize) Get() *GetMaxCreateOrderSize {
	return v.value
}

func (v *NullableGetMaxCreateOrderSize) Set(val *GetMaxCreateOrderSize) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMaxCreateOrderSize) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMaxCreateOrderSize) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMaxCreateOrderSize(val *GetMaxCreateOrderSize) *NullableGetMaxCreateOrderSize {
	return &NullableGetMaxCreateOrderSize{value: val, isSet: true}
}

func (v NullableGetMaxCreateOrderSize) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMaxCreateOrderSize) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


